### ISSUE TITLE
It doesn't turn off Do Not Disturb

### ISSUE THREAD

**Issue by tino** [karaggeorge/kap-do-not-disturb#1]
Which is annoying, because it causes me to miss notifications!

**Comment by karaggeorge** [comment]
Is this something you can reproduce consistently? Or did it happen if Kap crashed for some reason while recording?

**Comment by tino** [comment]
Not anymore, it now seems to work. I don't think Kap crashed.

I must admit that I have switched back to Licecap in the mean time. Less polished but _way_ faster. I mean the file is there when you hit stop. Kap always made me wait a bit too long to export.

Sorry for the noise and thanks for building though!
